### ISSUE TITLE
backup error

### ISSUE THREAD

**Issue by skyw33** [mr-bjerre/hassio-remote-backup#13] opened 2018-10-19 03:59 UTC
I had this working with ssh keys, but somehow it broke.  I'm now getting the following log file...

```
Adding SSH key
Creating local backup: "Automated backup 2018-10-18 22:51"
Backup created: 
Copying .tar to /volume1/Documents/Backup\ files/Home\ Assistant on 192.168.1.158 using SCP
Error decoding json invalid character ':' after top-level value: 403: ForbiddenWarning: Permanently added '[192.168.1.158]:6341' (ECDSA) to the list of known hosts.
.tar: No such file or directory
```

Using Home Assistant 0.80.1 on raspberry pi using Hassos 1.10

**Comment by ArnoutVerbeken** [comment] 2018-10-19 20:37
Can be closed probably.  Duplicate of https://github.com/mr-bjerre/hassio-remote-backup/issues/9

**Closed as completed** 2018-10-24 16:37 UTC
Labels: duplicate
