### ISSUE TITLE
Tar file not found

### ISSUE THREAD

**Issue by Paul-dH** [mr-bjerre/hassio-remote-backup#9] opened 2018-10-06 10:19 UTC
Hi!

When starting the addon I get this in my log:
```
starting version 3.2.4
Adding SSH key
Creating local backup: "Automated backup 2018-10-06 12:08"
Backup created: 
Copying .tar to /data/Backup/Backups/Hassio on x.x.x.x using SCP
Error decoding json invalid character ':' after top-level value: 403: ForbiddenWarning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.
.tar: No such file or directory
```

My config:
```
{
  "ssh_host": "x.x.x.x",
  "ssh_port": 22,
  "ssh_user": "backupuser",
  "ssh_key": [
    "-----BEGIN RSA PRIVATE KEY-----",
    " Long key here ... ",
    "-----END RSA PRIVATE KEY-----"
  ],
  "remote_directory": "/data/Backup/Backups/Hassio",
  "zip_password": "",
  "keep_local_backup": "7"
}
```
I tested the SSH login with the private key to my nas, this works, also the path works. I've reviewd the run.sh script and it looks like the ${slug} variable is not available in the function `copy-backup-to-remote`

https://github.com/mr-bjerre/hassio-remote-backup/blob/496395a9d9ee3be5abd61f94b11a7898a14c3735/remote-backup/run.sh#L42

I'm on Hassio 79.3

**Comment by treos33** [comment] 2018-10-06 16:03
I'm having the same issue, also on 79.3. It looks like its not actually creating the local backup. When I go to the snapshots tab in Hassio there is nothing matching the name given in

> Creating local backup: "Automated backup ...."

Thanks

**Comment by nphil** [comment] 2018-10-07 06:54
Same issue here. Was working fine until the recent Hass update.

**Comment by ArnoutVerbeken** [comment] 2018-10-07 20:59
Same here...

**Comment by lissmeister** [comment] 2018-10-08 11:00
Same as the above for me too.

**Comment by NixBiks** [comment] 2018-10-08 14:15
Hello everyone. I am afraid that I am fed up with work and its not looking to change anytime soon. If there is anyone out there that have time and skills to fix the issues then you are more than welcome to pull request a solution. I'll try to prioritize fixing the issue but I can not guarantee this.

**Comment by NixBiks** [comment] 2018-10-12 11:49
Unfortunately I can't test this myself at this point. Will somebody confirm that release `v0.3.1` fixes the problem?

**Comment by ArnoutVerbeken** [comment] 2018-10-12 22:27
Sorry @mr-bjerre, but it's not solved.  Exact same issue as above.

**Comment by lissmeister** [comment] 2018-10-13 09:25
Sorry about that. It´s really strange though. The very same code works as intended when run as a local addon from the /addons-folder. I´ll try  to look into to it a bit more. Maybe there are permission differencies between how the addons are added.

**Comment by ArnoutVerbeken** [comment] 2018-10-19 20:36
Don't want to push, but any change this second fix can be implemented / tested?

**Comment by Paul-dH** [comment] 2018-10-20 20:41
Yeah, would be really great to get the add-on fixed and be able to use it :)

**Comment by NixBiks** [comment] 2018-10-24 16:38
Might be fixed in [v0.3.2](https://github.com/mr-bjerre/hassio-remote-backup/releases/tag/v0.3.2). Can somebody confirm? I have no ways of testing atm.

**Comment by Paul-dH** [comment] 2018-10-24 16:47
I've reinstalled the add-on repro and the add-on itself, but I get the same exact message with version 0.3.2

**Comment by tjorim** [comment] 2018-10-24 20:17
Won't be fixed in 0.3.2 since [this PR](https://github.com/mr-bjerre/hassio-addons/pull/2) is the one that actually affects it.

**Closed as completed** 2018-10-24 20:18 UTC
Labels: bug, help wanted, good first issue

**Comment by NixBiks** [comment] 2018-10-24 20:19
[PR](https://github.com/mr-bjerre/hassio-addons/pull/2) accepted so it should work now?

**Comment by ArnoutVerbeken** [comment] 2018-10-28 15:25
Thanks, works perfectly again! ;)
